### ISSUE TITLE
Support JSON6?

### ISSUE THREAD

**Issue by tomByrer** [Rich-Harris/golden-fleece#1]
Considered supporting the fresh JSON6?
Only a few more new things over JSON5, & faster streaming reading.

https://github.com/d3x0r/json6

**Comment by Rich-Harris** [comment]
Thanks, I wasn't aware of JSON6.

To be honest I'm not really sold on it. I don't think it's an improvement over JSON5 (other than the speed, which is due to the implementation and unrelated to the format). It's no longer valid JS (which means in lots of situations it won't syntax highlight correctly etc), and the various benefits (underscore-separated numbers?) are underwhelming in my opinion, and add complexity. So I'll close this.
